sojourner/config/routes.rb
# The Climate Corporation licenses this file to you under under the Apache
# License, Version 2.0 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.  Unless required by applicable law or agreed
# to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.  See the License for the specific language governing permissions
# and limitations under the License.
Rails.application.routes.draw do

  resources :templates, only: [:index, :show, :new, :create] do
    resources :template_versions, as: 'versions', only: [:new, :create, :show], param: :version, path: 'v' do
      resources :template_permission_changes, as: 'permissions', only: [:create],
                path: 'permission_changes'
      resource :sample_document, only: [:create]
    end
  end

  resources :template_schemas do
    member do
      get :clone
    end
  end

  post '/generate' => 'document_generation#generate', defaults: {format: :json}

  OkComputer::Engine.routes.draw do
    match '/' => 'ok_computer#index', via: [:get, :options]
  end

  root to: 'templates#index'
end

sojourner/app/views/templates/index.html.erb
<h1>Templates</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Type</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.id %></td>
        <td><%= template.name %></td>
        <td><%= template.type %></td>
        <td><%= link_to 'Show', template_path(template) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Create a template', [:new, :template], class: 'btn btn-primary' %>
</p>

sojourner/app/views/templates/new.html.erb
<h1>New Template</h1>

<%= form_for(@template) do |f| %>
  <%= render partial: 'shared/form_errors', locals: {record: @template} %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<br>
<p>
  <%= link_to 'Back', :templates %>
</p>

sojourner/app/views/templates/show.html.erb
<% if notice %>
  <br><p class="alert alert-success"><%= notice %></p>
<% end %>

<h1><%= @template.name %></h1>

<div class="panel panel-default">
  <div class="panel-heading">Created by:</div>
  <div class="panel-body"><%= @template.created_by %></div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Created at:</div>
  <div class="panel-body"><%= @template.created_at.to_formatted_s %></div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Updated at:</div>
  <div class="panel-body"><%= @template.updated_at.to_formatted_s %></div>
</div>

<h3>Versions</h3>
<% if @template.versions.exists? %>
  <table class="table">
    <thead>
      <tr>
        <th>Version</th>
        <th>Created by</th>
        <th>Created at</th>
        <th>Using Schema</th>
        <th>Enabled in Production</th>
        <th></th><th></th>
      </tr>
    </thead>
    <tbody>
      <% @template.versions.each do |template_version| %>
        <tr>
          <td><%= link_to "Version #{template_version.version}", template_version_path(@template, template_version.version)  %></td>
          <td><%= template_version.created_by %></td>
          <td><%= template_version.created_at.to_formatted_s %></td>

          <td><%= link_to "#{template_version.template_schema.id}", template_schema_path(template_version.template_schema) %></td>

          <td><%= template_version.ready_for_production? %></td>

          <td><%= link_to('enable', template_version_permissions_path(
                    @template, template_version.version, ready_for_production: true),
                    class: 'btn btn-primary',
                    method: :post,
                    data: { confirm: 'Are you sure?' }) if !template_version.ready_for_production? %></td>

          <td><%= link_to('disable', template_version_permissions_path(
                    @template, template_version.version, ready_for_production: false),
                    class: 'btn btn-primary',
                    method: :post,
                    data: { confirm: 'Are you sure?' }) if template_version.ready_for_production? %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>This template doesn't have any versions.</p>
<% end %>

<p>
  <%= link_to 'Create a version', new_template_version_path(@template), class: 'btn btn-primary' %>
</p>

<br>
<p><%= link_to 'Back', :templates %></p>