sojourner/config/routes.rb
# The Climate Corporation licenses this file to you under under the Apache
# License, Version 2.0 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.  Unless required by applicable law or agreed
# to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.  See the License for the specific language governing permissions
# and limitations under the License.
Rails.application.routes.draw do

  resources :templates, only: [:index, :show, :new, :create] do
    resources :template_versions, as: 'versions', only: [:new, :create, :show], param: :version, path: 'v' do
      resources :template_permission_changes, as: 'permissions', only: [:create],
                path: 'permission_changes'
      resource :sample_document, only: [:create]
    end
  end

  resources :template_schemas do
    member do
      get :clone
    end
  end

  post '/generate' => 'document_generation#generate', defaults: {format: :json}

  OkComputer::Engine.routes.draw do
    match '/' => 'ok_computer#index', via: [:get, :options]
  end

  root to: 'templates#index'
end

sojourner/app/models/template_single_version.rb
# The Climate Corporation licenses this file to you under under the Apache
# License, Version 2.0 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.  Unless required by applicable law or agreed
# to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.  See the License for the specific language governing permissions
# and limitations under the License.
class TemplateSingleVersion < ActiveRecord::Base
  attr_accessor :file, :ready_for_prod, :storage_type

  belongs_to :template

  # schemas can be associated with multiple templates.
  belongs_to :template_schema

  has_one :sample_document, as: :template_version

  has_one :file_location,
          as: :storable,
          class_name: "StorageLocation"

  has_many :permission_changes,
           as: :template_version,
           class_name: "TemplatePermissionChange"

  before_validation do
    ensure_version
    ensure_permissions
    ensure_file_location
  end

  validates :template,
            :template_schema,
            :created_by,
            :version,
            :permission_changes,
            :file_location,
            :file,
            presence: true

  validates :version, uniqueness: { scope: :template_id }
  validate :ensure_contiguous_versions

  delegate :file_saved?, to: :file_location

  after_initialize do
    @ready_for_prod ||= false
    @storage_type ||= StorageLocation::DEFAULT_TYPE[Rails.env]
  end

  def ready_for_production?
    permission_changes.order(created_at: :desc)
                      .limit(1)
                      .pluck(:ready_for_production)
                      .pop
  end

  def validate_input_data(input_data)
    schema = MultiJson.load(template_schema.json_schema)
    JSON::Validator.fully_validate(schema, input_data)
  end

  def render(input_data)
    template_file_stream = file_location.open.to_inputstream
    renderer = Java::WindwardTemplateRenderer.new(template_file_stream)

    input_data_root, input_data_body = MultiJson.load(input_data).first
    xml_input_data_stream = StringIO.new(
      input_data_body.to_xml(dasherize: false, root: input_data_root)
    ).to_inputstream

    document = Tempfile.new('document')
    document_stream = document.to_outputstream

    renderer.render(xml_input_data_stream, document_stream)

    document.open # Re-open in read mode
  end

  # required as storable
  def key_prefix
    "templates"
  end

  # required as storable
  def file_extension
    "docx"
  end

  private

  def ensure_version
    self.version ||= (template.versions.maximum(:version) || 0) + 1
  end

  def ensure_permissions
    self.permission_changes.new(
      ready_for_production: !!@ready_for_prod,
      created_by: self.created_by
    ) if self.permission_changes.empty?
  end

  def ensure_file_location
    self.build_file_location(
      file: file,
      type: storage_type
    ) if self.file_location.nil?
  end

  def ensure_contiguous_versions
    sibs = template.versions.pluck(:version) << self.version
    sibs.sort.each_with_index do |v, idx|
      unless (v == idx + 1)
        errors[:version] << "Can't skip version numbers"
      end
    end
  end

end

sojourner/app/views/template_single_versions/new.html.erb
<h1>New template single version</h1>

<%= form_for(@template_version, as: :template_version, url: template_versions_path(@template)) do |f| %>
  <%= render partial: "shared/form_errors", locals: {record: @template_version} %>

  <div class="form-group">
    <%= f.label :template_schema_id %><br>
    <%= f.select :template_schema_id, @template_schemas.map { |ts| [ts.name, ts.id] }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :file %>
    <%= f.file_field :file %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<br>
<p><%= link_to 'Back', template_path(@template) %></p>

sojourner/app/views/template_single_versions/show.html.erb
<h1>Template <%=@template_version.template.id %>: Version <%= @template_version.version %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Created by</th>
      <th>Created at</th>
      <th>Parent Template</th>
      <th>Enabled in production?</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @template_version.created_by %></td>
      <td><%= @template_version.created_at.to_formatted_s %></td>
      <td><%= link_to @template_version.template.name, template_path(@template_version.template) %></td>
      <!-- TODO: make ready_for_production on this page a toggle button -->
      <td><%= @template_version.ready_for_production? %></td>
    </tr>
  </tbody>
</table>

<div class="panel panel-default">
  <div class="panel-heading">Template file:</div>
  <div class="panel-body"><%= link_to @template_version.file_location.key, @template_version.file_location.read_link %> </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Sample Document:</div>
  <div class="panel-body">
    <% if @template_version.sample_document %>
      <%= link_to "template_#{@template.id}_version_#{@template_version.version}_SAMPLE.pdf", @template_version.sample_document.read_link, target: "_blank" %>
    <% else %>
      <%= link_to('Generate Sample', template_version_sample_document_path(
                    template_id: @template_version.template_id,
                    version_version: @template_version.version),
                    class: 'btn btn-primary',
                    method: :post) %>
    <% end %>
  </div>
</div>

<div class="panel-group" role="tablist">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="template-schema">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse-schema">
          <span style="text-decoration:underline;">
            JSON Schema for validating input_data for a request with this template_version
          </span>
        </a>
      </h4>
    </div>
    <div id="collapse-schema" class="panel-collapse collapse" role="tabpanel">
      <div class="panel-body">
        <pre><%= beautify_json(@template_version.template_schema.json_schema) %></pre>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="json-stub">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse-stub">
          <span style="text-decoration:underline;">
            Example JSON stub for POSTing a request with this template version
          </span>
        </a>
      </h4>
    </div>
    <div id="collapse-stub" class="panel-collapse collapse in" role="tabpanel">
      <div class="panel-body">
        <pre><%= beautify_json(@template_version.template_schema.json_stub) %></pre>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="permissions">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse-permissions">
          <span style="text-decoration:underline;">
            Permissions History
          </span>
        </a>
      </h4>
    </div>
    <div id="collapse-permissions" class="panel-collapse collapse" role="tabpanel">
      <div class="panel-body">
        <table class="table" id='permission-changes'>
          <thead>
            <tr>
              <th>Ready_for_production?</th>
              <th>Created By</th>
              <th>Created at</th>
            </tr>
          </thead>
          <tbody>
            <% @template_version.permission_changes.reverse.each_with_index do |permission_change, idx| %>
            <tr>
              <td ><%= permission_change.ready_for_production %></td>
              <td><%= permission_change.created_by %></td>
              <td><%= permission_change.created_at %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>