sojourner/config/routes.rb
# The Climate Corporation licenses this file to you under under the Apache
# License, Version 2.0 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.  Unless required by applicable law or agreed
# to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.  See the License for the specific language governing permissions
# and limitations under the License.
Rails.application.routes.draw do

  resources :templates, only: [:index, :show, :new, :create] do
    resources :template_versions, as: 'versions', only: [:new, :create, :show], param: :version, path: 'v' do
      resources :template_permission_changes, as: 'permissions', only: [:create],
                path: 'permission_changes'
      resource :sample_document, only: [:create]
    end
  end

  resources :template_schemas do
    member do
      get :clone
    end
  end

  post '/generate' => 'document_generation#generate', defaults: {format: :json}

  OkComputer::Engine.routes.draw do
    match '/' => 'ok_computer#index', via: [:get, :options]
  end

  root to: 'templates#index'
end

sojourner/app/models/template_schema.rb
# The Climate Corporation licenses this file to you under under the Apache
# License, Version 2.0 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.  Unless required by applicable law or agreed
# to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.  See the License for the specific language governing permissions
# and limitations under the License.
class TemplateSchema < ActiveRecord::Base
  acts_as_paranoid

  validates :name, presence: true

  validates :json_schema_properties, presence: true
  with_options if: :json_schema_properties_valid? do |template_schema|
    template_schema.validates :json_schema_properties, json: true
    template_schema.validate  :json_schema_properties_includes_root_property
    template_schema.validate  :json_schema_properties_doesnt_include_ids
    template_schema.validates :json_schema_properties, json: {
      as_schema: true,
      value: :json_schema
    }

    template_schema.validates :json_stub, json: {
      schema: ->(record) { MultiJson.load(record.json_schema) }
    }, allow_blank: true
  end

  validates :json_stub, presence: true

  validates :created_by, presence: true

  has_many :template_single_versions

  def self.new_clone(template_schema)
    new(
      template_schema.attributes.slice("json_schema_properties", "json_stub")
        .merge(name: "CLONE OF #{template_schema.name} (edit me)")
    )
  end

  def json_schema
    schema = {type: :object, additionalProperties: false}

    properties = MultiJson.try(:load, json_schema_properties)
    root = properties.try(:keys).try(:first)

    schema[:required] = [root] if root
    schema[:properties] = properties if properties

    schema.to_json
  end

  def immutable?
    persisted? && !template_single_versions.empty?
  end

  private

  def json_schema_properties_valid?
    errors[:json_schema_properties].blank?
  end

  def json_schema_properties_includes_root_property
    properties = MultiJson.load(json_schema_properties)
    unless properties.is_a?(Hash) && properties.length == 1
      errors[:json_schema_properties] << "must include exactly one root element"
    end
  end

  def json_schema_properties_doesnt_include_ids
    if json_schema_properties =~ /"id":/
      errors[:json_schema_properties] << "'id' attribute is not supported"
    end
  end
end

sojourner/app/controllers/template_schemas_controller.rb
# The Climate Corporation licenses this file to you under under the Apache
# License, Version 2.0 (the "License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.  Unless required by applicable law or agreed
# to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.  See the License for the specific language governing permissions
# and limitations under the License.
class TemplateSchemasController < UiController
  before_action :set_template_schema, only: [:show, :edit, :update, :destroy, :clone]
  before_action :verify_immutability, only: [:edit, :update, :destroy]

  # GET /template_schemas
  def index
    @template_schemas = TemplateSchema.all
  end

  # GET /template_schemas/1
  def show
  end

  # GET /template_schemas/new
  def new
    @template_schema = TemplateSchema.new
  end

  # GET /template_schemas/1/edit
  def edit
  end

  # POST /template_schemas
  def create
    @template_schema = TemplateSchema.new(template_schema_params)

    @template_schema.created_by = current_user_id

    respond_to do |format|
      if @template_schema.save
        format.html { redirect_to template_schema_path(@template_schema), notice: 'Template schema was successfully created.' }
        format.json { render :show, status: :created, location: @template_schema }
      else
        format.html { render :new }
        format.json { render json: @template_schema.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /template_schemas/:id/clone
  def clone
    @template_schema = TemplateSchema.new_clone(@template_schema)
    render :new
  end

  # PATCH/PUT /template_schemas/1
  def update
    respond_to do |format|
      if @template_schema.update(template_schema_params)
        format.html { redirect_to template_schema_path(@template_schema), notice: 'Template schema was successfully updated.' }
        format.json { render :show, status: :ok, location: @template_schema }
      else
        format.html { render :edit }
        format.json { render json: @template_schema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /template_schemas/1
  def destroy
    @template_schema.destroy
    respond_to do |format|
      format.html { redirect_to template_schemas_url, notice: 'Template schema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_template_schema
    @template_schema = TemplateSchema.find(params[:id])
  end

  def template_schema_params
    params.require(:template_schema)
          .permit(:name, :json_schema_properties, :json_stub)
  end

  def verify_immutability
    if @template_schema.immutable?
      render text: "A template is already using this schema", status: :forbidden
    end
  end
end

sojourner/app/views/template_schemas/_form.html.erb
<%= form_for(@template_schema) do |f| %>
  <%= render partial: "shared/form_errors", locals: {record: @template_schema} %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :json_schema_properties %>
    <%= f.text_area :json_schema_properties, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :json_stub %>
    <%= f.text_area :json_stub, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

sojourner/app/views/template_schemas/edit.html.erb
<h1>Editing template schema <em><%= @template_schema.name %></em></h1>

<%= render 'form' %>

<br>
<p>
  <%= link_to 'Show', @template_schema %> |
  <%= link_to 'Back', template_schemas_path %>
</p>

sojourner/app/views/template_schemas/index.html.erb
<h1>Template Schemas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created by</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @template_schemas.each do |template_schema| %>
      <tr>
        <td><%= template_schema.name %></td>
        <td><%= template_schema.created_by %></td>
        <td><%= template_schema.created_at.to_formatted_s %></td>
        <td><%= template_schema.updated_at.to_formatted_s %></td>
        <td><%= link_to 'Show', template_schema %></td>
        <% if !template_schema.immutable? %>
          <td><%= link_to 'Edit', [:edit, template_schema] %></td>
          <td><%= link_to 'Destroy', template_schema, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td><%= link_to 'Clone', clone_template_schema_path(template_schema) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'Create a template schema', [:new, :template_schema], class: 'btn btn-primary' %>
</p>

sojourner/app/views/template_schemas/new.html.erb
<h1><%= @template_schema.name || "New Template Schema" %></h1>

<%= render 'form' %>

<br>

<p><%= link_to 'Back', :template_schemas %></p>

sojourner/app/views/template_schemas/show.html.erb
<% if notice %>
  <br><p class="alert alert-success"><%= notice %></p>
<% end %>

<h1><%= @template_schema.name %></h1>

<% if @template_schema.immutable? %>
  <p>
    This schema has been used by a template already, and cannot be edited or altered.
  </p>
  <p>
    You can still use it for new templates, if you don't need to change it.
    (It will show up in the drop-down when you create a new template version.)
  </p>
  <p>
  Or, you can clone it and edit the copy.
<% else %>
  <p>
  <%= link_to('Edit', [:edit, @template_schema], class: 'btn btn-primary') %>
<% end %>

<%= link_to('Clone', clone_template_schema_path(@template_schema),
            class: 'btn btn-primary') %>
</p>

<div class="panel panel-default">
  <div class="panel-heading">Json schema:</div>
  <div class="panel-body">
    <pre><%= beautify_json(@template_schema.json_schema) %></pre>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Json stub:</div>
  <div class="panel-body">
    <pre><%= beautify_json(@template_schema.json_stub) %></pre>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Created by:</div>
  <div class="panel-body"><%= @template_schema.created_by %></div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Created at:</div>
  <div class="panel-body"><%= @template_schema.created_at.to_formatted_s %></div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Updated at:</div>
  <div class="panel-body"><%= @template_schema.updated_at.to_formatted_s %></div>
</div>

<%= link_to 'Back', :template_schemas %>